### PR TITLE
Updating Continuous Integration using GitHub Actions and VSCode settings

### PR DESCRIPTION
**Pull request by ehsteve**
This pull request cleans up and expands the continuous integration so that it is easier to see where problems arise
* Testing workflow: all testing is now done on multiple platforms and multiple versions of python on each platform.
* Formatting and Linting workflow: uses flake8 and black and specifies which patterns to use. The list is copied from the sunpy project. Only tested on Python 3.8 and linux.
* Building docs: Tests whether docs can be successfully built using sphinx. Only tested on Python 3.8 and linux.

This PR also includes VSCode settings to ensure that the dev environment is helping to ensure that tests do not fail. It uses black and flake8 are installed in the environment.

### CODE REVIEW

**Comment by ehsteve** [comment]
@tonyastrofig Could you make sure that these VSCode settings work properly on your system please?

**Comment by tonyastrofig** [comment]
@ehsteve sure I'll see if they work.  I assume the best way to do that Is "Merge pull request" and then rerun the docker?

**Comment by ehsteve** [comment]
Don't merge! You can check out this branch and get it on your machine for testing. Let me know if you don't know how to do that.

**Comment by tonyastrofig** [comment]
Glad I asked.  Yep, I know how to check out the branch.  I'll give it a try.  Thanks.

**Comment by ehsteve** [comment]
I see an issue that the vscode settings are set both in the `.vscode` folder as well as the `.devcontainer`. @tonyastrofig would mind investigating this?

**Comment by tonyastrofig** [comment]
Yes, I'll look into the vscode settings in both folders and see which is preferable.

**Review by tonyastrofig — COMMENTED** [review]
The docker file from the github-actions branch seems to run the container just fine, but I noticed a few things:
1 - VS Code noted that pylance was being used so that was correctly updated from last time.
2 - Windows popped up a message saying "Docker Desktop has detected that you shared a Windosw file into a WSL 2 container, which may perform poorly"
3 - VS Code reports 1 problem from devcontainer.json:
This is deprecated, the new recommended way to configure your default shell is by creating a terminal profile in `#terminal.integrated.profiles.linux#` and setting its profile name as the default in `#terminal.integrated.defaultProfile.linux#`. This will currently take priority over the new profiles settings but that will change in the future.
Do you think we need to fix #2 or #3 or are they OK?

**Comment by tonyastrofig** [comment]
I'm continuing to research, but it seems like the vscode settings should all be in .devcontainer (since we're running in the container) and should be removed from .vscode.  I think that the .vscode settings.json file is being ignored right now but still looking into it.

**Comment by ehsteve** [comment]
@tonyastrofig could you look into #2? I can't use docker on my windows machine yet. Might as well fix #3. I'll go ahead and do that.

**Comment by ehsteve** [comment]
@tonyastrofig I fixed number 3.

**Comment by tonyastrofig** [comment]
@ehsteve I just pulled the latest and the Docker file runs with #1 (pylance) and #3 (deprecated terminal.integrated) both fixed.  And deleting the .vscode settings file didn't have any negative side effects.

**Comment by tonyastrofig** [comment]
@ehsteve The windows message from my comment #2 continues to appear.  Based on some internet searches it seems to be indicating that accessing files on the Windows host file system from a Linux container will perform slower than accessing files that are already in a Linux filesystem, similar to accessing files on a remote file share.  The recommended fix is to "store your source files in a WSL2 distro's file system (which you can bind mount to the container) or building your container image to include all the files needed rather than storing your files in the Windows file system."

As I'm not fluent in Docker, I'm not entirely sure which part of our setup is accessing Windows files.  Any thoughts?

**Comment by ehsteve** [comment]
That sounds like we can ignore this. This is how vscode works. It lets you work on files on your windows machine while running inside a container. Just curious but what is issuing this message? Docker?

**Comment by ehsteve** [comment]
If you are okay with it please update your review so we can merge.

**Review by tonyastrofig — APPROVED** [review]
Everything looks good and works on my VSCode

**Pull request merged**
